// <auto-generated />
using System;
using CostaRicaMusic.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CostaRicaMusic.DAL.Migrations
{
    [DbContext(typeof(CostaRicaMusicContext))]
    [Migration("20260406041446_AddSecondUser")]
    partial class AddSecondUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<string>("PortadaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Albumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2022,
                            ArtistaId = 1,
                            PortadaUrl = "images/albums/un-verano-sin-ti.jpg",
                            Titulo = "Un Verano Sin Ti"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2015,
                            ArtistaId = 2,
                            PortadaUrl = "images/albums/25.jpg",
                            Titulo = "25"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2015,
                            ArtistaId = 3,
                            PortadaUrl = "images/albums/a-head-full-of-dreams.jpg",
                            Titulo = "A Head Full of Dreams"
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2023,
                            ArtistaId = 4,
                            PortadaUrl = "images/albums/manana-sera-bonito.jpg",
                            Titulo = "Mañana Será Bonito"
                        },
                        new
                        {
                            Id = 5,
                            Anio = 2016,
                            ArtistaId = 5,
                            PortadaUrl = "images/albums/24k-magic.jpg",
                            Titulo = "24K Magic"
                        });
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Artista urbano y uno de los exponentes más conocidos del reggaetón y trap latino.",
                            ImagenUrl = "images/artists/badbunny.jpg",
                            Nombre = "Bad Bunny",
                            Pais = "Puerto Rico"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cantante británica reconocida por su potente voz y baladas pop.",
                            ImagenUrl = "images/artists/adele.jpg",
                            Nombre = "Adele",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Banda británica de pop rock alternativo con reconocimiento internacional.",
                            ImagenUrl = "images/artists/coldplay.jpg",
                            Nombre = "Coldplay",
                            Pais = "Reino Unido"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Cantante colombiana destacada en el género urbano y pop latino.",
                            ImagenUrl = "images/artists/karolg.jpg",
                            Nombre = "Karol G",
                            Pais = "Colombia"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Cantante y compositor estadounidense de pop, funk y R&B.",
                            ImagenUrl = "images/artists/brunomars.jpg",
                            Nombre = "Bruno Mars",
                            Pais = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            ArtistaId = 1,
                            AudioUrl = "audio/titi-me-pregunto.mp3",
                            Duracion = 240,
                            Nombre = "Tití Me Preguntó"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            ArtistaId = 1,
                            AudioUrl = "audio/ojitos-lindos.mp3",
                            Duracion = 258,
                            Nombre = "Ojitos Lindos"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            ArtistaId = 2,
                            AudioUrl = "audio/hello.mp3",
                            Duracion = 295,
                            Nombre = "Hello"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            ArtistaId = 2,
                            AudioUrl = "audio/send-my-love.mp3",
                            Duracion = 223,
                            Nombre = "Send My Love"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            ArtistaId = 3,
                            AudioUrl = "audio/hymn-for-the-weekend.mp3",
                            Duracion = 258,
                            Nombre = "Hymn for the Weekend"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            ArtistaId = 3,
                            AudioUrl = "audio/adventure-of-a-lifetime.mp3",
                            Duracion = 263,
                            Nombre = "Adventure of a Lifetime"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 4,
                            ArtistaId = 4,
                            AudioUrl = "audio/provenza.mp3",
                            Duracion = 210,
                            Nombre = "Provenza"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 4,
                            ArtistaId = 4,
                            AudioUrl = "audio/cairo.mp3",
                            Duracion = 200,
                            Nombre = "Cairo"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 5,
                            ArtistaId = 5,
                            AudioUrl = "audio/24k-magic.mp3",
                            Duracion = 227,
                            Nombre = "24K Magic"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 5,
                            ArtistaId = 5,
                            AudioUrl = "audio/thats-what-i-like.mp3",
                            Duracion = 206,
                            Nombre = "That's What I Like"
                        });
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.PlaylistCancion", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("CancionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId", "CancionId");

                    b.HasIndex("CancionId");

                    b.HasIndex("PlaylistId", "CancionId")
                        .IsUnique();

                    b.ToTable("PlaylistCanciones");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "admin@test.com",
                            FechaRegistro = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Admin",
                            PasswordHash = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "test@test.com",
                            FechaRegistro = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Usuario Test",
                            PasswordHash = "1234"
                        });
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Album", b =>
                {
                    b.HasOne("CostaRicaMusic.DAL.Entities.Artista", "Artista")
                        .WithMany("Albumes")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Cancion", b =>
                {
                    b.HasOne("CostaRicaMusic.DAL.Entities.Album", "Album")
                        .WithMany("Canciones")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CostaRicaMusic.DAL.Entities.Artista", "Artista")
                        .WithMany("Canciones")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Playlist", b =>
                {
                    b.HasOne("CostaRicaMusic.DAL.Entities.Usuario", "Usuario")
                        .WithMany("Playlists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.PlaylistCancion", b =>
                {
                    b.HasOne("CostaRicaMusic.DAL.Entities.Cancion", "Cancion")
                        .WithMany("PlaylistCanciones")
                        .HasForeignKey("CancionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRicaMusic.DAL.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistCanciones")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancion");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Album", b =>
                {
                    b.Navigation("Canciones");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Artista", b =>
                {
                    b.Navigation("Albumes");

                    b.Navigation("Canciones");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Cancion", b =>
                {
                    b.Navigation("PlaylistCanciones");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistCanciones");
                });

            modelBuilder.Entity("CostaRicaMusic.DAL.Entities.Usuario", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
